---
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 2017
env:
  node: true
globals:
  Promise: false
plugins:
  - promise
rules:
  block-scoped-var: 2
  callback-return: 2
  complexity: [2, 14]
  curly: [2, multi-or-nest, consistent]
  dot-location: [2, property]
  dot-notation: 2
  indent: [2, 2, SwitchCase: 1]
  linebreak-style: [2, unix]
  new-cap: 2
  no-console: 0
  no-else-return: 2
  no-eq-null: 2
  no-fallthrough: 2
  no-invalid-this: 2
  no-return-assign: 2
  no-shadow: 1
  no-trailing-spaces: 2
  no-use-before-define: [2, nofunc]
  no-var: 2
  quotes: [2, single, avoid-escape]
  semi: [2, always]
  strict: [2, global]
  valid-jsdoc: [2, requireReturn: false]

  promise/always-return: 2
  promise/no-return-wrap: 2
  promise/param-names: 2
  promise/catch-or-return: [2, allowThen: true]
  promise/no-native: 0
  promise/no-nesting: 1
  promise/no-promise-in-callback: 1
  promise/no-callback-in-promise: 1
  promise/avoid-new: 1
